### ISSUE TITLE
add pry/binding.pry for ruby?

### ISSUE THREAD

**Issue by aars** [ndbroadbent/git-remove-debug#2]

**Comment by ndbroadbent** [comment]
Sure, that would be awesome!

**Comment by ndbroadbent** [comment]
It would just need to be added here: https://github.com/ndbroadbent/git-remove-debug/blob/master/lib/matchers.rb#L4-L25

**Comment by ndbroadbent** [comment]
Sorry, going to close this for now, but PRs are welcome!
